# .github/workflows/chromatic.yml

# Workflow name
name: 'Build and publish library to NPM'

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Build Angular Componenets Library
        run: ng build angular-components-depot-library
      - name: Publish to NPM
        run: ng build angular-components-depot-library